import AsideNav from './components/AsideNav/AsideNav'
import Footer from './components/Footer/Footer'
import BottomNav from './components/bottomNav/BottomNav'
import Nav from './components/nav/nav'
import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Nav />
        {children}
        <BottomNav />
        <Footer />
        {/* added the develope branch */}
        </body>
    </html>
  )
}
